rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: checktrip
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: create