management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: checktrip-back
    description: An checktrip app
    author: David Rodriguez
    version: '@project.version@'
spring:
  profiles:
    active: dev
